name: update deno dependencies

on:
  schedule:
    - cron: '0 12 * * 5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Update dependency
        uses: hasundue/molt-action@v1
